import json
from pathlib import Path

from web3 import Web3


RPC_URL = "http://127.0.0.1:8545"

REGISTRY_ADDRESS = (
    "0x5FbDB2315678afecb367f032d93F642f64180aa3"
)

ARTIFACT_PATH = Path(
    "blockchain/artifacts/contracts/"
    "IssuerRegistry.sol/"
    "IssuerRegistry.json"
)


def load_registry_abi() -> list:
    """
    Load the IssuerRegistry ABI generated by Hardhat.
    """
    if not ARTIFACT_PATH.exists():
        raise FileNotFoundError(
            f"Contract artifact not found: {ARTIFACT_PATH}"
        )

    with ARTIFACT_PATH.open(
        "r",
        encoding="utf-8",
    ) as file:
        artifact = json.load(file)

    return artifact["abi"]


def connect_to_blockchain() -> Web3:
    """
    Connect to the local Hardhat JSON-RPC node.
    """
    web3 = Web3(
        Web3.HTTPProvider(RPC_URL)
    )

    if not web3.is_connected():
        raise ConnectionError(
            f"Could not connect to blockchain at {RPC_URL}"
        )

    return web3


def get_registry_contract(
    web3: Web3,
):
    """
    Return a Web3 contract instance for IssuerRegistry.
    """
    abi = load_registry_abi()

    checksum_address = (
        Web3.to_checksum_address(
            REGISTRY_ADDRESS
        )
    )

    return web3.eth.contract(
        address=checksum_address,
        abi=abi,
    )


def check_issuer_authorization(
    ukprn: int,
    issuer_did: str,
    verification_method: str,
) -> bool:
    """
    Check whether an issuer identity and verification
    method are currently authorised on-chain.
    """
    web3 = connect_to_blockchain()

    registry = get_registry_contract(
        web3
    )

    return registry.functions.isIssuerAuthorized(
        ukprn,
        issuer_did,
        verification_method,
    ).call()


def get_issuer_record(
    ukprn: int,
):
    """
    Retrieve the full issuer registry record.
    """
    web3 = connect_to_blockchain()

    registry = get_registry_contract(
        web3
    )

    return registry.functions.getIssuer(
        ukprn
    ).call()


if __name__ == "__main__":
    ukprn = 10005553

    issuer_did = (
        "did:example:issuer:"
        "ukprn-10005553"
    )

    verification_method = (
        "did:key:"
        "z6MkiiZELAGKMmDh6xpogFEMacqfvB8F7o5XU1Pq7hFvXfgU"
        "#"
        "z6MkiiZELAGKMmDh6xpogFEMacqfvB8F7o5XU1Pq7hFvXfgU"
    )

    print(
        "Connecting to:",
        RPC_URL,
    )

    web3 = connect_to_blockchain()

    print(
        "Blockchain connected:",
        web3.is_connected(),
    )

    print(
        "Chain ID:",
        web3.eth.chain_id,
    )

    print(
        "Latest block:",
        web3.eth.block_number,
    )

    record = get_issuer_record(
        ukprn
    )

    print(
        "\nON-CHAIN ISSUER RECORD"
    )

    print(
        "UKPRN:",
        record[0],
    )

    print(
        "Issuer DID:",
        record[1],
    )

    print(
        "Verification method:",
        record[2],
    )

    print(
        "Active:",
        record[3],
    )

    print(
        "Registered at:",
        record[4],
    )

    print(
        "Updated at:",
        record[5],
    )

    authorised = (
        check_issuer_authorization(
            ukprn,
            issuer_did,
            verification_method,
        )
    )

    print(
        "\nBlockchain authorization:",
        (
            "AUTHORIZED"
            if authorised
            else "NOT AUTHORIZED"
        ),
    )